name: CD
on:
  push:
      branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: chekout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: taysabarbosa
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: taysabarbosa/turtorial-argocd
          tags: ${{ env.github.sha}}, latest
